#!/usr/bin/python3
"""Command line interface for rfplayer library.

Usage:
  rfplayer [-v | -vv] [options]
  rfplayer [-v | -vv] [options] [--repeat <repeat>] (on|off|allon|alloff|up|down|stop|pair) <id>
  rfplayer (-h | --help)
  rfplayer --version

Options:
  -p --port=<port>   Serial port to connect to [default: /dev/ttyUSB0],
                       or TCP port in TCP mode.
  --baud=<baud>      Serial baud rate [default: 115200].
  --host=<host>      TCP mode, connect to host instead of serial port.
  --repeat=<repeat>  How often to repeat a command [default: 1].
  -m=<handling>      How to handle incoming packets [default: event].
  --ignore=<ignore>  List of device ids to ignore, wildcards supported.
  -h --help          Show this screen.
  -v                 Increase verbosity
  --version          Show version.
"""

import asyncio
import logging
import sys
from typing import Dict, Optional, Sequence, Type  # noqa: unused-import

# import pkg_resources
# from docopt import docopt

from rfpprotocol import (  # noqa: unused-import
    CommandSerialization,
    EventHandling,
    PacketHandling,
    ProtocolBase,
    RfplayerProtocol,
    create_rfplayer_connection,
)

PROTOCOLS = {
    "command": RfplayerProtocol,
    "event": EventHandling,
    "print": PacketHandling,
}  # type: Dict[str, Type[ProtocolBase]]

ALL_COMMANDS = ["on", "off", "allon", "alloff", "up", "down", "stop", "pair"]

import pprint


def event1_callback(event):
    pprint.pprint(event)


def main(
    argv: Sequence[str] = sys.argv[1:], loop: Optional[asyncio.AbstractEventLoop] = None
) -> None:
    """Parse argument and setup main program loop."""
    logging.basicConfig(level=logging.DEBUG)

    if not loop:
        loop = asyncio.get_event_loop()

    command = ALL_COMMANDS
    protocol_type = PROTOCOLS["command"]

    conn = create_rfplayer_connection(
        protocol=protocol_type,
        host="",
        port="",
        baud="",
        event_callback=event1_callback,
        loop=loop,
        ignore=([],),
    )

    transport, protocol = loop.run_until_complete(conn)

    # protocol.initialize()

    # assert isinstance(protocol, CommandSerialization)

    try:
        if command:
            assert isinstance(protocol, CommandSerialization)
            for _ in range(1):
                loop.run_until_complete(protocol.send_command_ack(None, command))
        else:
            loop.run_forever()
    except KeyboardInterrupt:
        # cleanup connection
        transport.close()
        loop.run_forever()
    finally:
        loop.close()


main()
