send_command:
  description: Send device command through RFPlayer.
  fields:
    command:
      name: Command
      description: The command to be sent.
      required: true
      example: "on"
      selector:
        text:
    device_id:
      name: Device ID
      description: RFLink device ID.
      required: true
      example: 2724069380
      selector:
        text:
